# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2017-01-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=30)),
                ('nr_faktury', models.CharField(max_length=30)),
                ('data_wystawienia', models.DateField()),
                ('data_sprzedazy', models.DateField()),
                ('termin_platnosci', models.DateField()),
                ('nazwa_nabywcy', models.CharField(max_length=160)),
                ('adres_nabywcy', models.CharField(max_length=160)),
                ('netto_23', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('vat_23', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('netto_8', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('vat_8', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('netto_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('vat_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('netto_0', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('netto_zw', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('naleznosc', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('korygujaca', models.BooleanField(default=False)),
                ('przyczyna_korekty', models.CharField(max_length=100)),
                ('nr_korygowanej', models.CharField(max_length=30)),
                ('data_korygowanej', models.DateField()),
                ('zaliczkowa', models.BooleanField(default=False)),
                ('odwrotne', models.BooleanField(default=False)),
                ('turystyka', models.BooleanField(default=False)),
                ('uwagi', models.CharField(max_length=160)),
            ],
        ),
    ]
