# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2017-01-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0002_faktura_nip_nabywcy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='data_korygowanej',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='nr_korygowanej',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='przyczyna_korekty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='termin_platnosci',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='uwagi',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
