# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-02-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0003_auto_20170128_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiersz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=30)),
                ('nazwa', models.CharField(max_length=100)),
                ('jm', models.CharField(max_length=3)),
                ('ilosc', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('cena_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('cena_brutto', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('upust', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True)),
                ('netto', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('brutto', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('stawka', models.CharField(max_length=2, null=True)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bra.Faktura')),
            ],
        ),
    ]
