# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-11 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0004_wiersz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSprzedazy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faktury', models.CharField(max_length=50)),
                ('wiersze', models.CharField(max_length=50, null=True)),
                ('do_rejestru', models.BooleanField(default=False)),
                ('rejestr', models.CharField(max_length=3)),
                ('konto_kon', models.CharField(max_length=20, null=True)),
                ('konto_spr', models.CharField(max_length=20, null=True)),
                ('ile_faktur', models.SmallIntegerField(default=0)),
                ('ile_wierszy', models.SmallIntegerField(default=0)),
                ('kiedy', models.DateTimeField(default=datetime.datetime.now)),
                ('kto', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='faktura',
            name='fak_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='faktura',
            name='kon_konto',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
