# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-11 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0005_auto_20170311_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsprzedazy',
            name='konto_kon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='importsprzedazy',
            name='konto_spr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='importsprzedazy',
            name='rejestr',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='importsprzedazy',
            name='wiersze',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
