# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-11 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0008_auto_20170311_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='firma',
        ),
        migrations.AddField(
            model_name='faktura',
            name='import_sprzedazy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bra.ImportSprzedazy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='nadpisane',
            field=models.SmallIntegerField(default=0),
        ),
    ]
