# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-12 17:00
from __future__ import unicode_literals

import bra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0009_auto_20170311_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsprzedazy',
            name='ile_0',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='ile_23',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='ile_5',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='ile_8',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='ile_zw',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importsprzedazy',
            name='faktury',
            field=models.FileField(upload_to=bra.models.sprzedaz_path),
        ),
        migrations.AlterField(
            model_name='importsprzedazy',
            name='wiersze',
            field=models.FileField(blank=True, null=True, upload_to=bra.models.sprzedaz_path),
        ),
    ]
