# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-12 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0010_auto_20170312_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsprzedazy',
            name='rejestr',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
