# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-12 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0011_auto_20170312_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsprzedazy',
            name='naleznosc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='netto_0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='netto_23',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='netto_5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='netto_8',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='netto_zw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='vat_23',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='vat_5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='vat_8',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
