# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0012_auto_20170312_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsprzedazy',
            name='do_numeru',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsprzedazy',
            name='od_numeru',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
