# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0014_auto_20170313_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faktura',
            old_name='kon_konto',
            new_name='konto_kon',
        ),
        migrations.AddField(
            model_name='faktura',
            name='konto_spr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
