# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-15 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0015_auto_20170314_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faktura',
            unique_together=set([('import_sprzedazy', 'ident')]),
        ),
    ]
