# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-19 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20191229_1548'),
        ('bra', '0017_kontrahent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportZakupow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_daty', models.DateField()),
                ('do_daty', models.DateField()),
                ('ile_faktur', models.SmallIntegerField(default=0)),
                ('ile_wierszy', models.SmallIntegerField(default=0)),
                ('od_zak_id', models.IntegerField(null=True)),
                ('do_zak_id', models.IntegerField(null=True)),
                ('kiedy', models.DateTimeField(default=datetime.datetime.now)),
                ('kto', models.CharField(max_length=10)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Firma')),
            ],
        ),
    ]
