# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-20 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0018_importzakupow'),
    ]

    operations = [
        migrations.AddField(
            model_name='importzakupow',
            name='ile_kon',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importzakupow',
            name='ile_lp_roz',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importzakupow',
            name='ile_nie_fa',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importzakupow',
            name='ile_podobne',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importzakupow',
            name='do_daty',
            field=models.DateField(verbose_name='Do daty'),
        ),
        migrations.AlterField(
            model_name='importzakupow',
            name='do_zak_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importzakupow',
            name='od_daty',
            field=models.DateField(verbose_name='Od daty'),
        ),
        migrations.AlterField(
            model_name='importzakupow',
            name='od_zak_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
