# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-20 21:20
from __future__ import unicode_literals

import app.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bra', '0019_auto_20200220_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='importzakupow',
            name='xls',
            field=app.model_fields.CompressedTextField(null=True, verbose_name='Plik kontrolny XLS'),
        ),
    ]
