# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-08-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonKrs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=20)),
                ('nazwa', models.CharField(max_length=160)),
                ('skrot', models.CharField(max_length=40)),
                ('ulica', models.CharField(max_length=40)),
                ('kod', models.CharField(max_length=20)),
                ('miejscowosc', models.CharField(max_length=30)),
                ('wojewodztwo', models.CharField(max_length=3)),
                ('kraj', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'kon_krs',
                'managed': False,
            },
        ),
    ]
