# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-02-19 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polon', '0002_auto_20170218_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='kiedy',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tworzenie',
            name='usunieto',
            field=models.DateTimeField(null=True),
        ),
    ]
