# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-02-19 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polon', '0004_auto_20170219_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='opis',
        ),
    ]
