# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-02-19 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polon', '0007_auto_20170219_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='opis',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='zlc_nazwa',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
