# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-02-20 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polon', '0009_auto_20170219_2308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faktura',
            unique_together=set([('tworzenie', 'id')]),
        ),
    ]
