# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-04-24 21:29
from __future__ import unicode_literals

import app.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paczka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data paczki')),
                ('cel', models.CharField(max_length=100, verbose_name='Cel kontroli')),
            ],
        ),
        migrations.CreateModel(
            name='Plik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=10, verbose_name='Kod pliku JPK')),
                ('dataod', models.DateField(verbose_name='Data Od')),
                ('datado', models.DateField(verbose_name='Data Do')),
                ('czesc', models.CharField(max_length=7, verbose_name='Miesi\u0105c cz\u0119\u015bci')),
                ('utworzony', models.DateTimeField(verbose_name='Utworzony')),
                ('xml', app.model_fields.CompressedTextField(null=True, verbose_name='Tre\u015b\u0107 e-maila')),
                ('paczka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paczka')),
            ],
        ),
    ]
