# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-04-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160424_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ana',
            fields=[
                ('anal_id', models.AutoField(primary_key=True, serialize=False)),
                ('numer_a', models.CharField(max_length=20)),
                ('nazwa_a', models.CharField(max_length=80)),
                ('wn_0', models.DecimalField(decimal_places=2, max_digits=16)),
                ('wn_1', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ma_0', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ma_1', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'db_table': 'fk_ana',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='plik',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='plik',
            name='paczka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pliki', to='app.Paczka'),
        ),
    ]
