# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-04-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160426_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syn',
            fields=[
                ('synt_id', models.AutoField(primary_key=True, serialize=False)),
                ('numer_s', models.CharField(max_length=3)),
                ('nazwa_s', models.CharField(max_length=40)),
                ('bilans', models.CharField(max_length=1)),
                ('spec', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'fk_syn',
                'managed': False,
            },
        ),
    ]
