# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-04-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_syn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(max_length=20, verbose_name=b'Tabela')),
                ('wiersze', models.IntegerField(verbose_name=b'Wiersze')),
                ('suma1', models.DecimalField(decimal_places=2, max_digits=16)),
                ('suma2', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('plik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podsumowania', to='app.Plik')),
            ],
        ),
    ]
