# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-04-27 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160427_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrl',
            name='suma1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='ctrl',
            name='wiersze',
            field=models.IntegerField(default=0, verbose_name=b'Wiersze'),
        ),
    ]
