# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-04-27 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzy',
            fields=[
                ('uzy_id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_uzy', models.CharField(max_length=10)),
            ],
        ),
    ]
