# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-04-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_uzy'),
    ]

    operations = [
        migrations.CreateModel(
            name='KsiOpi',
            fields=[
                ('ksi_id', models.AutoField(primary_key=True, serialize=False)),
                ('zaksieg', models.CharField(max_length=1)),
                ('uwagi', models.CharField(max_length=100)),
            ],
        ),
    ]
