# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-04-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ksiopi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksiopi',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uzy',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='plik',
            name='stan',
            field=models.CharField(choices=[('CZEKA', 'Oczekuje'), ('TWORZ', 'Tworzenie'), ('GOTOW', 'Gotowy')], default='CZEKA', max_length=10),
        ),
    ]
