# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-05-09 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160428_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dow',
            fields=[
                ('dow_id', models.AutoField(db_column=b'dow_id', primary_key=True, serialize=False)),
                ('nr_dowodu', models.CharField(max_length=10)),
                ('miesiac', models.CharField(max_length=7)),
                ('d_wyst', models.DateField()),
                ('d_ksieg', models.DateField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=16)),
                ('rodzaj', models.CharField(max_length=2)),
                ('numer', models.IntegerField()),
                ('lpoz', models.SmallIntegerField()),
                ('kto', models.IntegerField()),
                ('kiedy', models.DateField()),
                ('lp_dzi', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'fk_dow',
                'managed': False,
            },
        ),
    ]
