# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-05-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_fapopi_kon_magdok_magwiersz_zak_zlc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakZrv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konto4', models.CharField(max_length=20)),
                ('zaklad', models.CharField(max_length=3)),
                ('temat', models.CharField(max_length=10)),
                ('netto', models.DecimalField(decimal_places=2, default=0, max_digits=16, null=True)),
                ('stawka', models.CharField(max_length=2)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=16, null=True)),
                ('ip', models.CharField(max_length=1)),
                ('zrv', models.CharField(max_length=3)),
                ('odlicz', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'fk_zak_zrv',
                'managed': False,
            },
        ),
    ]
