# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-05-16 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_zakzrv'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ana',
            table='ana',
        ),
        migrations.AlterModelTable(
            name='dow',
            table='dow',
        ),
        migrations.AlterModelTable(
            name='fapopi',
            table='fap_opi',
        ),
        migrations.AlterModelTable(
            name='kon',
            table='kon',
        ),
        migrations.AlterModelTable(
            name='ksi',
            table='ksi',
        ),
        migrations.AlterModelTable(
            name='ksiopi',
            table='ksi_opi',
        ),
        migrations.AlterModelTable(
            name='magdok',
            table='mag_dok',
        ),
        migrations.AlterModelTable(
            name='magwiersz',
            table='mag_wiersz',
        ),
        migrations.AlterModelTable(
            name='syn',
            table='syn',
        ),
        migrations.AlterModelTable(
            name='uzy',
            table='sys_uzy',
        ),
        migrations.AlterModelTable(
            name='zak',
            table='zak',
        ),
        migrations.AlterModelTable(
            name='zakzrv',
            table='zak_zrv',
        ),
        migrations.AlterModelTable(
            name='zlc',
            table='zlc',
        ),
    ]
