# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-05-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_srtmkv_srtvat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZlcTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linia', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'zlc_txt',
                'managed': False,
            },
        ),
    ]
