# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-06-01 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_plik_odkad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plik',
            name='stan',
            field=models.CharField(choices=[('W KOLEJCE', 'Oczekuje'), ('TWORZENIE', 'Tworzenie'), ('GOTOWY', 'Gotowy')], default='W KOLEJCE', max_length=10),
        ),
    ]
