# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-06-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160601_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysPar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=30)),
                ('nazwa', models.CharField(blank=True, max_length=40)),
                ('wartosc', models.CharField(blank=True, max_length=120)),
                ('uwagi', models.CharField(blank=True, max_length=300)),
                ('poprawne', models.CharField(blank=True, max_length=60)),
                ('sysid', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'db_table': 'sys_par',
                'managed': False,
            },
        ),
    ]
