# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-06-05 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_syspar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_slo', models.CharField(max_length=5)),
                ('spokod', models.CharField(max_length=20)),
                ('pnazwa', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'spo',
                'managed': False,
            },
        ),
    ]
