# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-06-15 21:44
from __future__ import unicode_literals

import app.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_spo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wyciag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_rachunku', models.CharField(max_length=28, verbose_name=b'Nr rachunku')),
                ('nr_wyciagu', models.IntegerField(verbose_name=b'Nr wyciagu')),
                ('waluta', models.CharField(max_length=3, verbose_name=b'Waluta')),
                ('kod', models.CharField(max_length=4, verbose_name=b'Kod operacji')),
                ('data', models.DateField(verbose_name=b'Data operacji')),
                ('kwota', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('opis', models.CharField(max_length=255, verbose_name=b'Opis operacji')),
                ('podmiot', models.CharField(max_length=255, verbose_name=b'Nazwa podmiotu')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
            ],
        ),
        migrations.AlterField(
            model_name='plik',
            name='xml',
            field=app.model_fields.CompressedTextField(null=True, verbose_name='Zawarto\u015b\u0107 pliku JPK'),
        ),
    ]
