# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-06-16 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20160615_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='rachunek',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
