# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160421010813 on 2016-06-17 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20160617_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defzrv',
            options={'managed': False, 'ordering': ['zrv_id']},
        ),
    ]
