# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-07-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_magdzial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='magazyn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
