# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-07-08 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20160708_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magkart',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='magtowar',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
