# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-07-09 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20160708_2359'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='magkart',
            table='mag_kart',
        ),
        migrations.AlterModelTable(
            name='magtowar',
            table='mag_towar',
        ),
    ]
