# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-07-13 15:09
from __future__ import unicode_literals

import app.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20160711_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('text', app.model_fields.CompressedTextField(null=True, verbose_name='Odpowied\u017a na Status')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_time', models.DateTimeField()),
                ('sign_xml', app.model_fields.CompressedTextField(verbose_name='Plik do podpisania')),
                ('aes_key', models.CharField(max_length=44)),
                ('aes_iv', models.CharField(max_length=24)),
                ('aes', app.model_fields.CompressedTextField(verbose_name='Plik do wys\u0142ania')),
                ('xml_name', models.CharField(max_length=20)),
                ('xml_len', models.IntegerField()),
                ('xml_hash', models.CharField(max_length=44)),
                ('zip_name', models.CharField(max_length=20)),
                ('zip_len', models.IntegerField()),
                ('zip_hash', models.CharField(max_length=24)),
                ('xades_time', models.DateTimeField(null=True)),
                ('xades', app.model_fields.CompressedTextField(null=True, verbose_name='Plik podpisany')),
                ('init_time', models.DateTimeField(null=True)),
                ('init_code', models.IntegerField(null=True)),
                ('init_text', app.model_fields.CompressedTextField(null=True, verbose_name='Odpowied\u017a na InitUploadSigned')),
                ('put_time', models.DateTimeField(null=True)),
                ('put_code', models.IntegerField(null=True)),
                ('put_text', app.model_fields.CompressedTextField(null=True, verbose_name='Odpowied\u017a na Upload')),
                ('finish_time', models.DateTimeField(null=True)),
                ('finish_code', models.IntegerField(null=True)),
                ('finish_text', app.model_fields.CompressedTextField(null=True, verbose_name='Odpowied\u017a na FinishUpload')),
                ('reference', models.CharField(max_length=32, null=True)),
                ('jpk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Plik')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='status',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusy', to='app.Storage'),
        ),
    ]
