# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-07-13 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20160713_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='aes',
            new_name='jpk_aes',
        ),
        migrations.AddField(
            model_name='storage',
            name='enc_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
