# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-07-13 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20160713_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='enc_key',
            field=models.TextField(),
        ),
    ]
