# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-07-16 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20160714_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plik',
            name='paczka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pliki', to='app.Paczka'),
        ),
        migrations.AlterField(
            model_name='plik',
            name='stan',
            field=models.CharField(choices=[(b'W KOLEJCE', b'Oczekuje'), (b'TWORZENIE', b'Tworzenie'), (b'GOTOWY', b'Gotowy')], default=b'W KOLEJCE', max_length=15),
        ),
    ]
