# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-08-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_fakres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zrodlo', models.CharField(max_length=10)),
                ('dokument', models.CharField(max_length=20)),
                ('blad', models.TextField()),
                ('jpk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Plik')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
