# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-08-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_ctrl_xls'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='nazwa',
            field=models.CharField(max_length=40, null=True, verbose_name=b'Nazwa'),
        ),
    ]
