# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-08-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_plik_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plik',
            name='nazwa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Nazwa'),
        ),
    ]
