# -*- coding: utf-8 -*-
# Generated by Django 1.9.8.dev20160628165209 on 2016-08-30 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20160824_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='bramka',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
