# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20160928105123 on 2016-10-06 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20160902_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='xades',
            new_name='xades_xml',
        ),
        migrations.AlterField(
            model_name='ctrl',
            name='tabela',
            field=models.CharField(max_length=20, verbose_name='Tabela'),
        ),
        migrations.AlterField(
            model_name='ctrl',
            name='wiersze',
            field=models.IntegerField(default=0, verbose_name='Wiersze'),
        ),
        migrations.AlterField(
            model_name='plik',
            name='kod',
            field=models.CharField(max_length=10, verbose_name='Kod pliku JPK'),
        ),
        migrations.AlterField(
            model_name='plik',
            name='nazwa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='plik',
            name='odkad',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Odkad'),
        ),
        migrations.AlterField(
            model_name='plik',
            name='stan',
            field=models.CharField(default='W KOLEJCE', max_length=15),
        ),
        migrations.AlterField(
            model_name='wyciag',
            name='data',
            field=models.DateField(verbose_name='Data operacji'),
        ),
        migrations.AlterField(
            model_name='wyciag',
            name='kod',
            field=models.CharField(max_length=4, verbose_name='Kod operacji'),
        ),
        migrations.AlterField(
            model_name='wyciag',
            name='nr_rachunku',
            field=models.CharField(max_length=28, verbose_name='Nr rachunku'),
        ),
        migrations.AlterField(
            model_name='wyciag',
            name='nr_wyciagu',
            field=models.IntegerField(verbose_name='Nr wyciagu'),
        ),
        migrations.AlterField(
            model_name='wyciag',
            name='opis',
            field=models.CharField(max_length=255, verbose_name='Opis operacji'),
        ),
        migrations.AlterField(
            model_name='wyciag',
            name='podmiot',
            field=models.CharField(max_length=255, verbose_name='Nazwa podmiotu'),
        ),
        migrations.AlterField(
            model_name='wyciag',
            name='waluta',
            field=models.CharField(max_length=3, verbose_name='Waluta'),
        ),
    ]
