# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161003200552 on 2016-10-18 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20161006_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='sign_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
