# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2016-12-13 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20161116_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaczenie', models.CharField(max_length=10)),
                ('db_ostatnia', models.CharField(max_length=20)),
                ('db_rok', models.IntegerField()),
                ('nip', models.CharField(max_length=10, verbose_name='NIP')),
                ('nazwa', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('adres', models.CharField(max_length=50, verbose_name='Adres')),
                ('regon', models.CharField(max_length=15, verbose_name='Regon')),
                ('wojewodztwo', models.CharField(max_length=20, verbose_name='Województwo')),
                ('powiat', models.CharField(max_length=50, verbose_name='Powiat')),
                ('gmina', models.CharField(max_length=50, verbose_name='Gmina')),
                ('ulica', models.CharField(max_length=30, verbose_name='Ulica')),
                ('nr_domu', models.CharField(max_length=10, verbose_name='Nr domu')),
                ('nr_lokalu', models.CharField(max_length=5, verbose_name='Nr lokalu', null= True)),
                ('miejscowosc', models.CharField(max_length=50, verbose_name='Miejscowość')),
                ('kod_pocztowy', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('poczta', models.CharField(max_length=50, verbose_name='Poczta')),
                ('kod_urzedu', models.CharField(max_length=4, verbose_name='Kod US')),
                ('rdok', models.CharField(max_length=5, verbose_name='Słownik dokumentów')),
                ('wszystkie_konta', models.BooleanField()),
                ('save_jpk_xls', models.BooleanField()),
                ('save_ctrl_xls', models.BooleanField()),
            ],
        ),
    ]
