# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2016-12-13 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

def inicjalizacja_firmy(apps, schema_editor):
    
    Firma= apps.get_model("app", "Firma")
    
    if settings.FIRMA == 'gig': 
        
        Firma.objects.create(
                             
            oznaczenie= 'gig',
            db_ostatnia= 'fk16',
            db_rok= 2016,
                                 
            nip= '6340126016',
            nazwa= 'Główny Instytut Górnictwa',
            adres= 'Katowice 40-166, ul. Gwarków 1',
            regon= '000023461',
            wojewodztwo= 'śląskie',
            powiat= 'm. Katowice',
            gmina= 'm. Katowice',
            ulica= 'Plac Gwarków',
            nr_domu= '1',
            miejscowosc= 'Katowice',
            kod_pocztowy= '40-166',
            poczta= 'Katowice',
            kod_urzedu= '2471',
            
            rdok= 'RDOKU',
            wszystkie_konta= False,
            save_jpk_xls= True,
            save_ctrl_xls= True,                             
        )
        
    if settings.FIRMA == 'ichp': 
        
        Firma.objects.create(
                             
            oznaczenie= 'ichp',
            db_ostatnia= 'fk16',
            db_rok= 2016,
                                 
            nip= '5250007939',
            nazwa= 'Instytut Chemii Przemysłowej, im. prof. I. Mościckiego',
            adres= 'Warszawa 01-793, ul. Rydygiera 8',
            regon= '000045161',
            wojewodztwo= 'mazowieckie',
            powiat= 'warszawski',
            gmina= 'Warszawa-Centrum',
            ulica= 'Rydygiera',
            nr_domu= '8',
            miejscowosc= 'Warszawa',
            kod_pocztowy= '01-793',
            poczta= 'Warszawa',
            kod_urzedu= '1471',
            
            rdok= 'RDOK',
            wszystkie_konta= True,
            save_jpk_xls= False,
            save_ctrl_xls= False,                               
        )
        
                
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_firma'),
    ]

    operations = [
        migrations.RunPython(inicjalizacja_firmy),                   
    ]
