# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2016-12-15 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20161213_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plik',
            name='paczka',
        ),
        migrations.DeleteModel(
            name='Paczka',
        ),
    ]
