# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2016-12-15 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20161215_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='rdok',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='save_ctrl_xls',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='save_jpk_xls',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='wszystkie_konta',
        ),
    ]
