# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2017-02-01 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20161215_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='cel_zlozenia',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
