# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2017-02-01 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_plik_cel_zlozenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='wariant',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
