# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-02-18 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20170217_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dan_id',
            new_name='job_id',
        ),
    ]
