# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-02-08 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20170311_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='plik',
            name='cel_zlozenia',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
