# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-02-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20180208_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='adres',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='gmina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gmina'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='kod_urzedu',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Kod US'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='nr_domu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nr domu'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='poczta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poczta'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='powiat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Powiat'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='regon',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Regon'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='ulica',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='wojewodztwo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Województwo'),
        ),
    ]
