# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-08-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_firma_ostatni_plik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='ostatni_plik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firma_ostatni', to='app.Plik'),
        ),
    ]
