# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-10-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20180804_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='blad',
            name='level',
            field=models.CharField(default='error', max_length=10),
        ),
    ]
