# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-12-08 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_blad_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='krs',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='NrKRS'),
        ),
    ]
