# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2019-12-29 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_firma_krs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='krs',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Nr KRS'),
        ),
    ]
