# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20191229_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='api_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Api url'),
        ),
    ]
