# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20200221_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='vat7',
            field=models.CharField(blank=True, choices=[('M', 'Miesięczna'), ('K', 'Kwartalna')], max_length=1, null=True, verbose_name='Deklaracja VAT'),
        ),
        migrations.AddField(
            model_name='plik',
            name='kod_systemowy',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='plik',
            name='wariant_formularza',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plik',
            name='wersja_schemy',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
