# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20200226_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='telefon',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefon'),
        )
    ]
