# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_deklaracja_element'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deklaracja',
            old_name='kwota1',
            new_name='kwota',
        ),
        migrations.RenameField(
            model_name='deklaracja',
            old_name='lp1',
            new_name='lp',
        ),
        migrations.RemoveField(
            model_name='deklaracja',
            name='kwota2',
        ),
        migrations.AlterField(
            model_name='deklaracja',
            name='rodzaj',
            field=models.CharField(max_length=1, verbose_name='Rodzaj'),
        ),
    ]
