# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20200228_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeklaracjaPoz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wariant', models.SmallIntegerField(default=21)),
                ('grupa', models.CharField(max_length=1, verbose_name='Grupa')),
                ('lp', models.SmallIntegerField()),
                ('rodzaj', models.CharField(max_length=1, verbose_name='Rodzaj')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('element', models.CharField(blank=True, max_length=30, null=True, verbose_name='Element')),
            ],
        ),
    ]
