# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-28 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_deklaracjapoz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deklaracja',
            old_name='lp',
            new_name='numer',
        ),
        migrations.RenameField(
            model_name='deklaracjapoz',
            old_name='lp',
            new_name='numer',
        ),
    ]
