# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20200228_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='deklaracjapoz',
            name='sumowanie',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sumowanie'),
        ),
    ]
