# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-29 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_deklaracjapoz_sumowanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='deklaracjapoz',
            name='x',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deklaracjapoz',
            name='y',
            field=models.SmallIntegerField(null=True),
        ),
    ]
