# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-03-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_auto_20200229_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='deklaracjapoz',
            name='strona',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Strona deklaracji'),
        ),
        migrations.AddField(
            model_name='deklaracjapoz',
            name='typ',
            field=models.CharField(default='D', max_length=1, verbose_name='Typ'),
        ),
    ]
