# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-03-12 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20200304_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='kod_systemowy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plik',
            name='wersja_schemy',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
