# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-05-06 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20200312_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='api_auth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Klucz API'),
        ),
    ]
