# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-11-19 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_firma_api_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='korekta',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
