# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-12-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='klu3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
