# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-12-06 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0002_auto_20181205_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='oblicz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
