# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-12-06 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0003_pozycja_oblicz'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='zalezne',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
