# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-12-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0004_pozycja_zalezne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='oblicz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
