# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-12-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0006_pozycja_kontener'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='wymagana',
            field=models.BooleanField(default=False),
        ),
    ]
