# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-12-08 22:04
from __future__ import unicode_literals

import app.model_fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0007_pozycja_wymagana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dodatkowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', app.model_fields.CompressedTextField(null=True, verbose_name='Opis')),
                ('nazwa', models.CharField(max_length=55)),
                ('zawartosc', app.model_fields.CompressedTextField(null=True, verbose_name='Zawartość')),
            ],
        ),
        migrations.CreateModel(
            name='Podatek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klucz', models.CharField(max_length=20)),
                ('element', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=250)),
                ('rb_lacznie', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('rb_kapitalowe', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('rb_inne', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('pp_art', models.CharField(max_length=5, null=True)),
                ('pp_ust', models.CharField(max_length=5, null=True)),
                ('pp_pkt', models.CharField(max_length=5, null=True)),
                ('pp_lit', models.CharField(max_length=5, null=True)),
                ('rp_lacznie', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('rp_kapitalowe', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('rp_inne', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Wprowadzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
                ('opis', app.model_fields.CompressedTextField(null=True, verbose_name='Opis')),
            ],
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='kod_pkd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p2_data_do',
            field=models.DateField(null=True, verbose_name='Działa do'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p2_data_do_opis',
            field=models.CharField(max_length=250, null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p2_data_od',
            field=models.DateField(null=True, verbose_name='Działa od'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p4_dane_laczne',
            field=models.BooleanField(default=False, verbose_name='Dane łączne'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p5a_kontynuacja',
            field=models.BooleanField(default=True, verbose_name='Założenie kontynuacji'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p5b_bez_zagrozenia',
            field=models.BooleanField(default=True, verbose_name='Bez zagrożenia kontynuacji'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p5c_zagrozenia',
            field=app.model_fields.CompressedTextField(null=True, verbose_name='Zawartość pliku JPK'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p6a_po_polaczeniu',
            field=models.BooleanField(default=False, verbose_name='Po połączeniu'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p6b_polaczenie',
            field=app.model_fields.CompressedTextField(null=True, verbose_name='Opis połączenia'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p7a_zasady',
            field=app.model_fields.CompressedTextField(null=True, verbose_name='Opis zasad'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p7b_wycena',
            field=app.model_fields.CompressedTextField(null=True, verbose_name='Opis wyceny'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p7c_wynik',
            field=app.model_fields.CompressedTextField(null=True, verbose_name='Opis wyniku'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p7d_spraw',
            field=app.model_fields.CompressedTextField(null=True, verbose_name='Opis sprawozdania'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='sporzadzone',
            field=models.DateField(default=datetime.date.today, verbose_name='Data sporządzenia'),
        ),
        migrations.AddField(
            model_name='wprowadzenie',
            name='sprawozdanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sf.Sprawozdanie'),
        ),
        migrations.AddField(
            model_name='podatek',
            name='sprawozdanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sf.Sprawozdanie'),
        ),
        migrations.AddField(
            model_name='dodatkowe',
            name='sprawozdanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sf.Sprawozdanie'),
        ),
    ]
