# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-12-08 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0008_auto_20181208_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p5b_bez_zagrozenia',
            new_name='bez_zagrozenia',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p4_dane_laczne',
            new_name='dane_laczne',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p2_data_do',
            new_name='data_do',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p2_data_do_opis',
            new_name='data_do_opis',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p2_data_od',
            new_name='data_od',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p5a_kontynuacja',
            new_name='kontynuacja',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p6a_po_polaczeniu',
            new_name='po_polaczeniu',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p6b_polaczenie',
            new_name='polaczenie',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p7d_spraw',
            new_name='spraw',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p7b_wycena',
            new_name='wycena',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p7c_wynik',
            new_name='wynik',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p5c_zagrozenia',
            new_name='zagrozenia',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='p7a_zasady',
            new_name='zasady',
        ),
    ]
