# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2018-12-13 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0010_raport_tabela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='sporzadzone',
            new_name='p0_data_sporzadzenia',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='dane_laczne',
            new_name='p4_laczne',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='bez_zagrozenia',
            new_name='p5_brak_zagrozen',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='kontynuacja',
            new_name='p5_kontynuacja',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='zagrozenia',
            new_name='p5_opis_zagrozen',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='polaczenie',
            new_name='p6_metoda',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='po_polaczeniu',
            new_name='p6_po_polaczeniu',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='spraw',
            new_name='p7_spraw',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='wycena',
            new_name='p7_wycena',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='wynik',
            new_name='p7_wynik',
        ),
        migrations.RenameField(
            model_name='sprawozdanie',
            old_name='zasady',
            new_name='p7_zasady',
        ),
        migrations.RemoveField(
            model_name='sprawozdanie',
            name='data_do',
        ),
        migrations.RemoveField(
            model_name='sprawozdanie',
            name='data_do_opis',
        ),
        migrations.RemoveField(
            model_name='sprawozdanie',
            name='data_od',
        ),
        migrations.RemoveField(
            model_name='sprawozdanie',
            name='kod_pkd',
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_gmina',
            field=models.CharField(default='', max_length=36, verbose_name='Gmina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_kod_kraju',
            field=models.CharField(default='PL', max_length=2, verbose_name='Kod kraju'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_kod_pocztowy',
            field=models.CharField(default='', max_length=8, verbose_name='Kod pocztowy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_krs',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Numer KRS'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_miejscowosc',
            field=models.CharField(default='', max_length=56, verbose_name='Miejscowość'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_nazwa_firmy',
            field=models.CharField(default='', max_length=255, verbose_name='Pełna nazwa firmy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_nip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Identyfikator podatkowy (NIP)'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_nr_domu',
            field=models.CharField(default='', max_length=9, verbose_name='Nr domu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_nr_lokalu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nr lokalu'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_pkd',
            field=models.CharField(default='', max_length=100, verbose_name='Przedmiot działalności jednostki'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_poczta',
            field=models.CharField(default='', max_length=56, verbose_name='Poczta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_powiat',
            field=models.CharField(default='', max_length=36, verbose_name='Powiat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_ulica',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Ulica'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p1_wojewodztwo',
            field=models.CharField(default='', max_length=36, verbose_name='Województwo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p2_data_do',
            field=models.DateField(null=True, verbose_name='Działa do'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p2_data_do_opis',
            field=models.CharField(max_length=250, null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p2_data_od',
            field=models.DateField(null=True, verbose_name='Działa od'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p3_data_do',
            field=models.DateField(default=None, verbose_name='Koniec okresu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='p3_data_od',
            field=models.DateField(default=None, verbose_name='Początek okresu'),
            preserve_default=False,
        ),
    ]
