# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2019-01-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0012_auto_20181213_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='el',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
