# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2019-12-29 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0013_pozycja_el'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pozycja',
            options={'ordering': ['klu1']},
        ),
        migrations.AlterField(
            model_name='raport',
            name='sprawozdanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raporty', to='sf.Sprawozdanie'),
        ),
        migrations.AlterField(
            model_name='wprowadzenie',
            name='sprawozdanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uszczegolowienia', to='sf.Sprawozdanie'),
        ),
    ]
