# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2016-11-30 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasDow',
            fields=[
                ('kpw_id', models.AutoField(primary_key=True, serialize=False)),
                ('kasa', models.CharField(max_length=2)),
                ('rodzaj', models.CharField(max_length=2, null=True)),
                ('numer', models.IntegerField(null=True)),
                ('stan', models.CharField(max_length=1, null=True)),
                ('nr_pra', models.CharField(max_length=6, null=True)),
                ('nazwa', models.CharField(max_length=240, null=True)),
                ('lacznie', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ksi', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'kas_dow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KasPoz',
            fields=[
                ('kpo_id', models.AutoField(primary_key=True, serialize=False)),
                ('lp', models.SmallIntegerField(null=True)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=16)),
                ('rach', models.CharField(max_length=30, null=True)),
                ('opis', models.CharField(max_length=80, null=True)),
                ('operacja', models.CharField(max_length=2, null=True)),
                ('konto', models.CharField(max_length=20, null=True)),
                ('ksi', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'kas_poz',
                'managed': False,
            },
        ),
    ]
