# -*- coding: utf-8 -*-
# Generated by Django 1.9.11.dev20161013150334 on 2017-01-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0003_zakpoz'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagNumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=2)),
                ('korekta', models.CharField(max_length=1)),
                ('rok', models.SmallIntegerField()),
                ('numer', models.IntegerField()),
            ],
            options={
                'db_table': 'mag_numer',
                'ordering': ['dzial', 'symbol', 'rok'],
                'managed': False,
            },
        ),
    ]
