# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-09 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0005_sysdan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysKli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=10)),
                ('nazwa', models.CharField(blank=True, max_length=40)),
                ('rok', models.SmallIntegerField()),
                ('na_podst', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sys_kli',
                'managed': False,
            },
        ),
    ]
