# -*- coding: utf-8 -*-
# Generated by Django 1.9.13.dev20170130170755 on 2017-03-13 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0006_syskli'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='magnumer',
            table='_mag_numer',
        ),
    ]
