# -*- coding: utf-8 -*-
# Generated by Django 1.9.14.dev20170906233242 on 2020-02-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0007_auto_20170313_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefNum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rejestr', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=2)),
                ('rodzaj', models.CharField(max_length=3)),
                ('korekta', models.CharField(max_length=1)),
                ('okres', models.CharField(max_length=7)),
                ('nastepny', models.IntegerField()),
            ],
            options={
                'db_table': '_def_num',
                'ordering': ['rejestr', 'symbol', 'rodzaj', 'okres'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FakZaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('numer', models.CharField(max_length=15)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'db_table': 'fak_zaf',
                'managed': False,
            },
        ),
    ]
